spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

